version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - default

  api-service:
    container_name: api-service
#    image: luongquoctay87/api-service:1.0-SNAPSHOT
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./src/main/resources/.env
    ports:
      - '8181:8181'
    depends_on:
      - postgres
    networks:
      - default

#  prometheus:
#    image: "prom/prometheus"
#    container_name: prometheus
#    restart: unless-stopped
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - '9090:9090'
#    networks:
#      - default
#
#  grafana:
#    image: "grafana/grafana"
#    container_name: grafana
#    restart: unless-stopped
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=password
#    ports:
#      - '3000:3000'
#    links:
#      - prometheus:prometheus
#    volumes:
#      - grafana:/var/lib/grafana
#    networks:
#      - default

networks:
  default:
    name: api-network

volumes:
  postgres:
#  grafana:
