scrape_configs:
  - job_name: 'api-service'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: [ 'api-service:8181' ]
        labels:
          application: 'API Service Application'