spring:
  application:
    name: api-service

server:
  port: 8181
  forward-headers-strategy: framework

api:
  info:
    title: API Services
    description: API to fetch review details for application
    version: 1.0.0
    terms-of-service: https://company.com/terms/
    contact:
      name: SOFTWARE CO., LTD
      email: contact@company.com
      url: https://company.com/
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'

#AWS properties
cloud:
  aws:
    region:
      static: ap-southeast-1
    stack:
      auto: false
    credentials:
      accessKey: ${ACCESS_KEY:xxx}
      secretKey: ${SECRET_KEY:yyy}
      bucketName: ${BUCKET_NAME:zzz}

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error